// For swapping categories with url routes
interface StringMap {
  [key: string]: string;
}

export const categoriesToRoutesConversion: StringMap = {
  "Auto Detailing Supplies": "supplies",
  "Auto Detailing Accessories": "accessories",
  "Brushes-Car Wash": "brushes",
  "Sponges &amp; Applicators": "sponges-applicators",
  "Brushes-Detail": "brushes-detailing",
  "Auto Detailing Products": "detailing-products",
  "Hand and Machine Waxes": "hand-machine-waxes",
  "Hand Tools &amp; Blades": "hand-tools",
  "Machine Compounds / Paint Pre-Cleaners": "compounds-precleaners",
  "Floor Mats": "floor-mats",
  "Bottles/Sprayers": "bottles-sprayers",
  "All Purpose Cleaners and Degreasers": "degreasers",
  Microfiber: "microfiber",
  "Air/Water Guns &amp; Hose": "water-hoses",
  "Paints/Markers": "paints-markers",
  "Car Wash Soaps": "soaps",
  "Flags/Paperwork": "flags-paperwork",
  "Machine and Hand Polishes / Glazes": "glazes",
  "Carpet Mask/Covers": "carpet-covers",
  "Air Freshner / Perfumes": "perfumes",
  "Vacuum Accessories": "vacuum-accessories",
  "Clay Bars": "clay",
  "Interior and Tire Dressings": "dressings",
  "Steel Wool": "steel-wool",
  "Buffing Pads": "buffing-pads",
  Aerosols: "aerosols",
  "Safety Items": "safety-items",
  Mitts: "mitts",
  "Glass Cleaners": "glass-cleaners",
  "Power Tools": "power-tools",
  "Towels &amp; Chamois": "towel-chamois",
};

export const routeToCategoryConversion = {
  supplies: "Auto Detailing Supplies",
  accessories: "Auto Detailing Accessories",
  brushes: "Brushes-Car Wash",
  "sponges-applicators": "Sponges &amp; Applicators",
  "brushes-detailing": "Brushes-Detail",
  "detailing-products": "Auto Detailing Products",
  "hand-machine-waxes": "Hand and Machine Waxes",
  "hand-tools": "Hand Tools &amp; Blades",
  "compounds-precleaners": "Machine Compounds / Paint Pre-Cleaners",
  "floor-mats": "Floor Mats",
  "bottles-sprayers": "Bottles/Sprayers",
  degreasers: "All Purpose Cleaners and Degreasers",
  microfiber: "Microfiber",
  "water-hoses": "Air/Water Guns &amp; Hose",
  "paints-markers": "Paints/Markers",
  soaps: "Car Wash Soaps",
  "flags-paperwork": "Flags/Paperwork",
  glazes: "Machine and Hand Polishes / Glazes",
  "carpet-covers": "Carpet Mask/Covers",
  perfumes: "Air Freshner / Perfumes",
  "vacuum-accessories": "Vacuum Accessories",
  clay: "Clay Bars",
  dressings: "Interior and Tire Dressings",
  "steel-wool": "Steel Wool",
  "buffing-pads": "Buffing Pads",
  aerosols: "Aerosols",
  "safety-items": "Safety Items",
  mitts: "Mitts",
  "glass-cleaners": "Glass Cleaners",
  "power-tools": "Power Tools",
  "towel-chamois": "Towels &amp; Chamois",
};
